### ISSUE TITLE
Link to the .exe here

### ISSUE THREAD

**Issue by YakuzaSuske** [DaxEleven/Rule34.xxx-Downloader#9]
https://drive.google.com/file/d/1ZtA-YbniCJ5WKlMqxAAE1Wc3KdwaWXnG/view?usp=sharing

**Comment by Alejin96** [comment]
> https://drive.google.com/file/d/1ZtA-YbniCJ5WKlMqxAAE1Wc3KdwaWXnG/view?usp=sharing

Did you convert this "portable" version? I remember it was actually an installer or something. I recently changed my computer and when I try to reinstall the app I find that the link is now private...

**Comment by Dax-Eleven** [comment]
Bugs fixed in version 1.0.3
This isn't an installer, but already unpacked files
I ditched the installer for the sake of privacy
Also, if someone can make a portable version, it'll be very good

The new version can be downloaded from my 2nd repository:
https://github.com/Dax-Eleven/Rule34.xxx-Downloader

**Comment by DaxEleven** [comment]
Link updated

**Comment by Alejin96** [comment]
Thank you very much! Thank you for the effort to update the application
